Testing adding Titanium Asteroid from new documentation
Followed instructions in new documentation.

Needed to additional add requirements in files like World, WorldApi,
UpdateProperties etc. that were not part of the existing documentation
which I realize was in process.

I think I did everything correct. Here are the error codes:

/Users/jonathanmar/Dev/pharcoder/src/common/Starcoder.js:83
                    local.prototype[key] = val;
                                         ^

TypeError: Cannot set property '_lineColor' of undefined
    at Starcoder.consolidateBody
(/Users/jonathanmar/Dev/pharcoder/src/common/Starcoder.js:83:42)
    at Starcoder.initBodies
(/Users/jonathanmar/Dev/pharcoder/src/common/Starcoder.js:110:14)
    at module.exports.init
(/Users/jonathanmar/Dev/pharcoder/src/server/components/PhysicsWorldInte
rface.js:60:14)
    at Starcoder.implementFeature
(/Users/jonathanmar/Dev/pharcoder/src/common/Starcoder.js:242:20)
    at Starcoder.init
(/Users/jonathanmar/Dev/pharcoder/src/server/Starcoder-server.js:27:10)
    at new Starcoder
(/Users/jonathanmar/Dev/pharcoder/src/common/Starcoder.js:21:15)
    at Object.<anonymous>
(/Users/jonathanmar/Dev/pharcoder/src/server.js:26:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)